// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ReCreating_NullType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReCreating_NullType));
        
        string IMigrationMetadata.Id
        {
            get { return "202105062307313_ReCreating_NullType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
